import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteShell } from "@/components/SiteShell";
import { GuideCard } from "@/components/GuideCard";
import { categories, categoryArticles, symptoms, titleCase } from "@/lib/site-data";

const infoPages: Record<string, { title: string; description: string; sections: { heading: string; body: string }[] }> = {
  about: { title: "About Housewise Guide", description: "A practical diagnostic reference for homeowners who want to understand what may be happening before deciding what to do next.", sections: [{ heading: "Why this site exists", body: "Homes communicate through symptoms: a stain, a sound, a smell, a temperature change, or a fixture behaving strangely. Housewise Guide organizes those clues into calm, useful explanations." }, { heading: "What we are—and are not", body: "We publish general educational information. We do not provide on-site diagnosis, emergency services, or a substitute for licensed professional judgment." }] },
  "editorial-policy": { title: "Editorial Policy", description: "How Housewise Guide researches, writes, updates, and connects homeowner problem guides.", sections: [{ heading: "Our method", body: "Each guide aims to identify common potential causes, explain how clues differ, list safe homeowner observations, and state when professional evaluation may be appropriate." }, { heading: "Evidence and uncertainty", body: "We avoid fake certainty, invented experience, unsupported statistics, and fabricated experts. Material safety or technical claims should be checked against primary or authoritative references. Reviewers may be identified only after their credentials and review are verified." }, { heading: "Corrections and updates", body: "Pages display update dates. Material corrections should be documented in the content registry and republished without changing the URL unless the search intent changes." }] },
  contact: { title: "Contact", description: "Contact information and correction guidance for Housewise Guide.", sections: [{ heading: "Corrections and feedback", body: "A public contact channel has not yet been configured. Before launch, replace this note with a monitored email address or accessible contact form. Never use this channel for emergencies." }] },
  privacy: { title: "Privacy Policy", description: "Starter privacy framework for Housewise Guide.", sections: [{ heading: "Current site behavior", body: "This initial version does not intentionally load advertising or analytics scripts. The hosting provider may process basic request data needed to deliver and secure the site." }, { heading: "Before tracking or ads launch", body: "This policy must be updated to identify the operator, vendors, cookies or storage, purposes, retention, user choices, and any jurisdiction-specific rights that actually apply. Obtain qualified legal review before relying on it." }] },
  terms: { title: "Terms & Disclaimer", description: "Important limitations for using Housewise Guide.", sections: [{ heading: "General information only", body: "Content is provided for general informational purposes and is not a substitute for inspection, diagnosis, repair, or advice from a qualified licensed professional who can evaluate actual conditions." }, { heading: "Safety and emergencies", body: "Do not rely on this site during an emergency. For fire, smoke, gas odor, carbon monoxide alarms, severe electrical hazards, structural movement, or immediate danger, leave the area when appropriate and contact emergency services or the relevant utility." }, { heading: "No guarantee", body: "A symptom can have multiple causes. Information may be incomplete or inapplicable to a particular home. Use judgment, follow manufacturer instructions, and comply with applicable codes and laws." }] }
};

export async function generateStaticParams() { return [...categories.map(({ slug }) => ({ category: slug })), ...Object.keys(infoPages).map((category) => ({ category }))]; }
export async function generateMetadata({ params }: { params: Promise<{ category: string }> }): Promise<Metadata> { const { category: slug } = await params; const info = infoPages[slug]; const category = categories.find((item) => item.slug === slug); if (!info && !category) return {}; const title = info?.title ?? `${category!.name} Problem Guides`; const description = info?.description ?? category!.intro; return { title, description, alternates: { canonical: `/${slug}/` }, openGraph: { title, description, images: [] }, twitter: { title, description, images: [] } }; }
export default async function CategoryPage({ params }: { params: Promise<{ category: string }> }) { const { category: slug } = await params; const info = infoPages[slug]; if (info) return <SiteShell><header className="page-hero compact"><p className="eyebrow">Housewise Guide</p><h1>{info.title}</h1><p>{info.description}</p></header><article className="prose legal">{info.sections.map((section) => <section key={section.heading}><h2>{section.heading}</h2><p>{section.body}</p></section>)}</article></SiteShell>; const category = categories.find((item) => item.slug === slug); if (!category) notFound(); const guides = categoryArticles(slug); return <SiteShell><header className="page-hero category-hero"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span aria-current="page">{category.name}</span></nav><p className="eyebrow">Home system</p><h1>{category.name} problem guides</h1><p>{category.intro} Start with a symptom or use the Problem Finder when you are not sure which guide fits.</p><Link className="button" href="/find-a-problem/">Use the Problem Finder</Link></header><section className="page-wrap category-body"><div><h2>Browse {category.name.toLowerCase()} symptoms</h2><div className="tag-links">{symptoms.slice(0,8).map((symptom) => <Link key={symptom} href={`/symptoms/${symptom}/`}>{titleCase(symptom)}</Link>)}</div></div><section><p className="eyebrow">Published guides</p><h2>Start here</h2>{guides.length ? <div className="guide-grid">{guides.map((article) => <GuideCard key={article.slug} article={article}/>)}</div> : <div className="empty-state"><strong>This hub is ready for its first guide.</strong><p>Topics will be added only when they answer a distinct search intent. Browse the complete library in the meantime.</p><Link href="/search/">Search all guides</Link></div>}</section></section></SiteShell>; }
